apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      name: my-react-app-pod
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: kangzu8743/apitest:v49
        imagePullPolicy: Always
        command: ['sh', '-c', 'echo xxx && sleep 6000']
        ports:
        - containerPort: 8080